### ISSUE TITLE
Cannot access protected methods using adapters' "this"

### ISSUE THREAD

**Issue by utybo** [eclipse/golo-lang#492] opened 2017-07-06 13:07 UTC
See this example : 

```
Adapter()
  : extends("javax.swing.SwingWorker")
  : implements("doInBackground", |this| {
    this: publish("Hello!", "Hi!", "HIIIII!")
  })
  : overrides("process", |super, this, bits| {
    foreach bit in bits {
      println(bit)
    }
  }): newInstance(): execute()
```

The call to "publish" fails with a NoSuchMethodError. This is because the `publish` method is protected in SwingWorker, and the Adapter fails to provide access to it. This makes it impossible to use SwingWorkers in Golo using adapters, and probably breaks other use cases, such as the ClassLoader case as described in the footnote of the report at #271 

> Another issue append when I invoke `this: findLoadedClass(...)` or `this: defineClass(...)`. Both are not found in this context. It is because both methods are protected and not overrided, and according the documentation of getDeclaredMethods and getMethods there's no direct way to obtain the inherited protected method of a class.

There does not seem to be any way around this that does not involve the less-than-secure setAccessible using Reflection. (Reflection also fails at this using getDeclaredMethods by the way, and the `^` operator also fails. Overriding the `publish` method in the adapter does not solve this either.)

**Comment by yloiseau** [comment] 2017-07-06 13:22
duplicate of #271

**Closed by yloiseau** 2017-07-06 13:22 UTC
Labels: duplicate
